apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-001
  provisioner: caicloud.io/nfs # or choose another name, must match deployment's env ENV_PROVISION_NAME'
parameters:
  server: 192.168.17.32
  exportPath: /root/zxq/data/nfs
  readOnly: false
