kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-nfs-pvc
  namespace: default
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-001"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
